# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d92f95d595b16e0e2b38738f0d30b7ea449c48d34d6a8e20380fdf72f1d75a1c1ab79d905effbefd14de08f1ccf6631b79bd99241d45b51bb8b6d64694854d27

test:
  secret_key_base: bda32f4623c02780a0ad8e82b9a970d7639a8064718e9d7d2323acebdd6ea1cbd1e6139bbf2d2acc74bc0c53fc2d6fd2075e9608152d43fb73f0974d8e7dff4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
